/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  // Delete existing entries
  await knex('employees').del();

  // Get required foreign key data
  const genders = await knex('genders').where('is_delete', false);
  const departments = await knex('departments').where('is_delete', false);
  const titles = await knex('titles').where('is_delete', false);
  const islands = await knex('islands').where('is_delete', false);

  // Helper function to get random item from array
  const getRandomItem = (array) => array.length > 0 ? array[Math.floor(Math.random() * array.length)] : null;

  // Insert sample employees data
  await knex('employees').insert([
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'John Doe',
      employee_email: 'john.doe@example.com',
      employee_mobile: '+6281234567890',
      employee_office_number: '+6221234567890',
      employee_phone: '+6281234567890',
      employee_address: 'Jl. Sudirman No. 123, Jakarta Selatan',
      employee_exmail_account: 'john.doe@company.com',
      employee_channel: 'john.doe@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz', // hashed password
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Jane Smith',
      employee_email: 'jane.smith@example.com',
      employee_mobile: '+6281234567891',
      employee_office_number: '+6221234567891',
      employee_phone: '+6281234567891',
      employee_address: 'Jl. Thamrin No. 456, Jakarta Pusat',
      employee_exmail_account: 'jane.smith@company.com',
      employee_channel: 'jane.smith@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Ahmad Rahman',
      employee_email: 'ahmad.rahman@example.com',
      employee_mobile: '+6281234567892',
      employee_office_number: '+6221234567892',
      employee_phone: '+6281234567892',
      employee_address: 'Jl. Gatot Subroto No. 789, Bandung',
      employee_exmail_account: 'ahmad.rahman@company.com',
      employee_channel: 'ahmad.rahman@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Maria Garcia',
      employee_email: 'maria.garcia@example.com',
      employee_mobile: '+6281234567893',
      employee_office_number: '+6221234567893',
      employee_phone: '+6281234567893',
      employee_address: 'Jl. Diponegoro No. 321, Surabaya',
      employee_exmail_account: 'maria.garcia@company.com',
      employee_channel: 'maria.garcia@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'David Wilson',
      employee_email: 'david.wilson@example.com',
      employee_mobile: '+6281234567894',
      employee_office_number: '+6221234567894',
      employee_phone: '+6281234567894',
      employee_address: 'Jl. Malioboro No. 654, Yogyakarta',
      employee_exmail_account: 'david.wilson@company.com',
      employee_channel: 'david.wilson@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Sarah Johnson',
      employee_email: 'sarah.johnson@example.com',
      employee_mobile: '+6281234567895',
      employee_office_number: '+6221234567895',
      employee_phone: '+6281234567895',
      employee_address: 'Jl. Kebon Jeruk No. 987, Jakarta Barat',
      employee_exmail_account: 'sarah.johnson@company.com',
      employee_channel: 'sarah.johnson@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Michael Brown',
      employee_email: 'michael.brown@example.com',
      employee_mobile: '+6281234567896',
      employee_office_number: '+6221234567896',
      employee_phone: '+6281234567896',
      employee_address: 'Jl. Pahlawan No. 111, Medan',
      employee_exmail_account: 'michael.brown@company.com',
      employee_channel: 'michael.brown@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Lisa Davis',
      employee_email: 'lisa.davis@example.com',
      employee_mobile: '+6281234567897',
      employee_office_number: '+6221234567897',
      employee_phone: '+6281234567897',
      employee_address: 'Jl. Veteran No. 222, Semarang',
      employee_exmail_account: 'lisa.davis@company.com',
      employee_channel: 'lisa.davis@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Robert Miller',
      employee_email: 'robert.miller@example.com',
      employee_mobile: '+6281234567898',
      employee_office_number: '+6221234567898',
      employee_phone: '+6281234567898',
      employee_address: 'Jl. Merdeka No. 333, Makassar',
      employee_exmail_account: 'robert.miller@company.com',
      employee_channel: 'robert.miller@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    },
    {
      employee_id: knex.raw('uuid_generate_v4()'),
      employee_name: 'Emily Wilson',
      employee_email: 'emily.wilson@example.com',
      employee_mobile: '+6281234567899',
      employee_office_number: '+6221234567899',
      employee_phone: '+6281234567899',
      employee_address: 'Jl. Dipatiukur No. 444, Bandung',
      employee_exmail_account: 'emily.wilson@company.com',
      employee_channel: 'emily.wilson@company.com',
      employee_activation_status: 'Activated',
      employee_disabled: false,
      employee_wechat_workplace: 'Not follow',
      employee_foto: null,
      password: '$2b$05$rQv8K9X2Y3Z4A5B6C7D8EeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz',
      title_id: getRandomItem(titles)?.title_id || null,
      gender_id: getRandomItem(genders)?.gender_id || null,
      department_id: getRandomItem(departments)?.department_id || null,
      island_id: getRandomItem(islands)?.island_id || null,
      created_by: knex.raw('(SELECT employee_id FROM employees LIMIT 1)'),
      is_delete: false
    }
  ]);
};
